USE controle_processos;

ALTER TABLE audits
    ADD COLUMN IF NOT EXISTS last_date_response DATE NULL AFTER start_date,
    ADD COLUMN IF NOT EXISTS deadline_label VARCHAR(80) NULL AFTER last_date_response,
    ADD COLUMN IF NOT EXISTS deadline_date DATE NULL AFTER deadline_label,
    ADD COLUMN IF NOT EXISTS deadline_is_current TINYINT(1) NOT NULL DEFAULT 0 AFTER deadline_date,
    ADD COLUMN IF NOT EXISTS flag_estimated TINYINT(1) NOT NULL DEFAULT 0 AFTER deadline_is_current,
    ADD COLUMN IF NOT EXISTS last_response_sent_date_diligence DATE NULL AFTER has_diligence,
    ADD COLUMN IF NOT EXISTS stage2_start_date DATE NULL AFTER last_response_sent_date_diligence,
    ADD COLUMN IF NOT EXISTS flag_stage2_diligence TINYINT(1) NOT NULL DEFAULT 0 AFTER stage2_start_date,
    ADD COLUMN IF NOT EXISTS stage2_date_last_response_diligence DATE NULL AFTER flag_stage2_diligence,
    ADD COLUMN IF NOT EXISTS stage2_preliminary_document VARCHAR(255) NULL AFTER stage2_date_last_response_diligence,
    ADD COLUMN IF NOT EXISTS stage2_final_report VARCHAR(255) NULL AFTER stage2_final_response,
    ADD COLUMN IF NOT EXISTS stage3_accord_report VARCHAR(255) NULL AFTER stage2_status,
    ADD COLUMN IF NOT EXISTS stage3_accord_report_date DATE NULL AFTER stage3_accord_report,
    ADD COLUMN IF NOT EXISTS monitoring1_start_date DATE NULL AFTER stage3_status,
    ADD COLUMN IF NOT EXISTS monitoring1_service_deadline_days INT NULL AFTER monitoring1_start_date,
    ADD COLUMN IF NOT EXISTS monitoring1_final_deadline DATE NULL AFTER monitoring1_service_deadline_days,
    ADD COLUMN IF NOT EXISTS monitoring1_final_response DATE NULL AFTER monitoring1_final_deadline,
    ADD COLUMN IF NOT EXISTS monitoring1_gap_days_from_report INT NULL AFTER monitoring1_final_response,
    ADD COLUMN IF NOT EXISTS monitoring1_next_monitoring_forecast DATE NULL AFTER monitoring1_gap_days_from_report,
    ADD COLUMN IF NOT EXISTS monitoring1_status VARCHAR(40) NULL AFTER monitoring1_next_monitoring_forecast,
    ADD COLUMN IF NOT EXISTS monitoring2_start_date DATE NULL AFTER monitoring1_status,
    ADD COLUMN IF NOT EXISTS monitoring2_service_deadline_days INT NULL AFTER monitoring2_start_date,
    ADD COLUMN IF NOT EXISTS monitoring2_final_deadline DATE NULL AFTER monitoring2_service_deadline_days,
    ADD COLUMN IF NOT EXISTS monitoring2_final_response DATE NULL AFTER monitoring2_final_deadline,
    ADD COLUMN IF NOT EXISTS monitoring2_gap_days_from_previous INT NULL AFTER monitoring2_final_response,
    ADD COLUMN IF NOT EXISTS monitoring2_next_monitoring_forecast DATE NULL AFTER monitoring2_gap_days_from_previous,
    ADD COLUMN IF NOT EXISTS monitoring2_status VARCHAR(40) NULL AFTER monitoring2_next_monitoring_forecast,
    ADD COLUMN IF NOT EXISTS monitoring3_start_date DATE NULL AFTER monitoring2_status,
    ADD COLUMN IF NOT EXISTS monitoring3_service_deadline_days INT NULL AFTER monitoring3_start_date,
    ADD COLUMN IF NOT EXISTS monitoring3_final_deadline DATE NULL AFTER monitoring3_service_deadline_days,
    ADD COLUMN IF NOT EXISTS monitoring3_final_response DATE NULL AFTER monitoring3_final_deadline,
    ADD COLUMN IF NOT EXISTS monitoring3_gap_days_from_previous INT NULL AFTER monitoring3_final_response,
    ADD COLUMN IF NOT EXISTS monitoring3_next_monitoring_forecast DATE NULL AFTER monitoring3_gap_days_from_previous,
    ADD COLUMN IF NOT EXISTS monitoring3_status VARCHAR(40) NULL AFTER monitoring3_next_monitoring_forecast,
    ADD COLUMN IF NOT EXISTS monitoring4_start_date DATE NULL AFTER monitoring3_status,
    ADD COLUMN IF NOT EXISTS monitoring4_service_deadline_days INT NULL AFTER monitoring4_start_date,
    ADD COLUMN IF NOT EXISTS monitoring4_final_deadline DATE NULL AFTER monitoring4_service_deadline_days,
    ADD COLUMN IF NOT EXISTS monitoring4_final_response DATE NULL AFTER monitoring4_final_deadline,
    ADD COLUMN IF NOT EXISTS monitoring4_gap_days_from_previous INT NULL AFTER monitoring4_final_response,
    ADD COLUMN IF NOT EXISTS monitoring4_next_monitoring_forecast DATE NULL AFTER monitoring4_gap_days_from_previous,
    ADD COLUMN IF NOT EXISTS monitoring4_status VARCHAR(40) NULL AFTER monitoring4_next_monitoring_forecast,
    ADD COLUMN IF NOT EXISTS control_summary LONGTEXT NULL AFTER related_processes;

ALTER TABLE audit_items
    ADD COLUMN IF NOT EXISTS status_geral VARCHAR(120) NULL AFTER item_control_point;
