CREATE TABLE IF NOT EXISTS inss_monitoring (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    source_key CHAR(64) NOT NULL UNIQUE,
    source_row INT UNSIGNED NULL,
    external_id INT UNSIGNED NULL,
    sei_process VARCHAR(80) NOT NULL,
    sent_office_number VARCHAR(100) NULL,
    sent_office_sei VARCHAR(80) NULL,
    office_date DATE NULL,
    sent_to_inss_date DATE NULL,
    inss_recipient_unit TEXT NULL,
    subject TEXT NULL,
    demand_type VARCHAR(255) NULL,
    demand_origin TEXT NULL,
    beneficiary TEXT NULL,
    cpf VARCHAR(255) NULL,
    benefit_number VARCHAR(120) NULL,
    deadline_status VARCHAR(80) NULL,
    status VARCHAR(100) NULL,
    inss_response_date DATE NULL,
    response_office_number VARCHAR(100) NULL,
    response_sei VARCHAR(80) NULL,
    conclusive_response VARCHAR(40) NULL,
    needs_follow_up VARCHAR(40) NULL,
    follow_up_date DATE NULL,
    follow_up_count INT UNSIGNED NULL,
    owner VARCHAR(160) NULL,
    priority VARCHAR(40) NULL,
    notes LONGTEXT NULL,
    sei_link TEXT NULL,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_inss_process (sei_process),
    INDEX idx_inss_status (status),
    INDEX idx_inss_deadline (deadline_status),
    INDEX idx_inss_owner (owner),
    INDEX idx_inss_priority (priority),
    INDEX idx_inss_sent_date (sent_to_inss_date),
    CONSTRAINT fk_inss_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_inss_updated_by FOREIGN KEY (updated_by) REFERENCES users(id) ON DELETE SET NULL
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
