Alias /controle "C:/xampp/htdocs/controle-de-processos/public"

<Directory "C:/xampp/htdocs/controle-de-processos/public">
    Options Indexes FollowSymLinks
    AllowOverride All
    Require all granted
    DirectoryIndex index.php
</Directory>
